.PHONY: all darwin linux windows

all: darwin linux windows

darwin:
	fyne package -os darwin -icon icon.png --release

linux:
	fyne package -os linux -icon icon.png --release

windows:
	fyne package -os windows -icon icon.png --release --app-id com.elementalmp4.sebschat